//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace eCardDialog.AUMRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="aum_6Binding", Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class AumService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback auEndeBearbeitenOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback detailDatenAbfragenOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadFormblattOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBesondereArbeitsunfaehigkeitsursacheCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDiagnoseCodeTypOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRueckdatierungsgrundCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSVTsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getZusatzdiagnoseCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback meldungAendernOperationCompleted;
        
        private System.Threading.SendOrPostCallback meldungAnlegenOperationCompleted;
        
        private System.Threading.SendOrPostCallback meldungStornierenOperationCompleted;
        
        private System.Threading.SendOrPostCallback meldungenFuerSvPersonSuchenOperationCompleted;
        
        private System.Threading.SendOrPostCallback selbstErstellteMeldungenSuchenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AumService() {
            this.Url = global::eCardDialog.Properties.Settings.Default.eCardDialog_AUMRef_AumService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event auEndeBearbeitenCompletedEventHandler auEndeBearbeitenCompleted;
        
        /// <remarks/>
        public event checkStatusCompletedEventHandler checkStatusCompleted;
        
        /// <remarks/>
        public event detailDatenAbfragenCompletedEventHandler detailDatenAbfragenCompleted;
        
        /// <remarks/>
        public event downloadFormblattCompletedEventHandler downloadFormblattCompleted;
        
        /// <remarks/>
        public event getBesondereArbeitsunfaehigkeitsursacheCodesCompletedEventHandler getBesondereArbeitsunfaehigkeitsursacheCodesCompleted;
        
        /// <remarks/>
        public event getDiagnoseCodeTypCompletedEventHandler getDiagnoseCodeTypCompleted;
        
        /// <remarks/>
        public event getRueckdatierungsgrundCodesCompletedEventHandler getRueckdatierungsgrundCodesCompleted;
        
        /// <remarks/>
        public event getSVTsCompletedEventHandler getSVTsCompleted;
        
        /// <remarks/>
        public event getZusatzdiagnoseCodesCompletedEventHandler getZusatzdiagnoseCodesCompleted;
        
        /// <remarks/>
        public event meldungAendernCompletedEventHandler meldungAendernCompleted;
        
        /// <remarks/>
        public event meldungAnlegenCompletedEventHandler meldungAnlegenCompleted;
        
        /// <remarks/>
        public event meldungStornierenCompletedEventHandler meldungStornierenCompleted;
        
        /// <remarks/>
        public event meldungenFuerSvPersonSuchenCompletedEventHandler meldungenFuerSvPersonSuchenCompleted;
        
        /// <remarks/>
        public event selbstErstellteMeldungenSuchenCompletedEventHandler selbstErstellteMeldungenSuchenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public aufSuchergebnis auEndeBearbeiten(string dialogId, string cardReaderId, long aufId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdSpecified, int aufIdVersion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdVersionSpecified, string arbeitsunfaehigBis, bool forceExecution, [System.Xml.Serialization.XmlIgnoreAttribute()] bool forceExecutionSpecified) {
            object[] results = this.Invoke("auEndeBearbeiten", new object[] {
                        dialogId,
                        cardReaderId,
                        aufId,
                        aufIdSpecified,
                        aufIdVersion,
                        aufIdVersionSpecified,
                        arbeitsunfaehigBis,
                        forceExecution,
                        forceExecutionSpecified});
            return ((aufSuchergebnis)(results[0]));
        }
        
        /// <remarks/>
        public void auEndeBearbeitenAsync(string dialogId, string cardReaderId, long aufId, bool aufIdSpecified, int aufIdVersion, bool aufIdVersionSpecified, string arbeitsunfaehigBis, bool forceExecution, bool forceExecutionSpecified) {
            this.auEndeBearbeitenAsync(dialogId, cardReaderId, aufId, aufIdSpecified, aufIdVersion, aufIdVersionSpecified, arbeitsunfaehigBis, forceExecution, forceExecutionSpecified, null);
        }
        
        /// <remarks/>
        public void auEndeBearbeitenAsync(string dialogId, string cardReaderId, long aufId, bool aufIdSpecified, int aufIdVersion, bool aufIdVersionSpecified, string arbeitsunfaehigBis, bool forceExecution, bool forceExecutionSpecified, object userState) {
            if ((this.auEndeBearbeitenOperationCompleted == null)) {
                this.auEndeBearbeitenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauEndeBearbeitenOperationCompleted);
            }
            this.InvokeAsync("auEndeBearbeiten", new object[] {
                        dialogId,
                        cardReaderId,
                        aufId,
                        aufIdSpecified,
                        aufIdVersion,
                        aufIdVersionSpecified,
                        arbeitsunfaehigBis,
                        forceExecution,
                        forceExecutionSpecified}, this.auEndeBearbeitenOperationCompleted, userState);
        }
        
        private void OnauEndeBearbeitenOperationCompleted(object arg) {
            if ((this.auEndeBearbeitenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.auEndeBearbeitenCompleted(this, new auEndeBearbeitenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public property[] checkStatus(string dialogId) {
            object[] results = this.Invoke("checkStatus", new object[] {
                        dialogId});
            return ((property[])(results[0]));
        }
        
        /// <remarks/>
        public void checkStatusAsync(string dialogId) {
            this.checkStatusAsync(dialogId, null);
        }
        
        /// <remarks/>
        public void checkStatusAsync(string dialogId, object userState) {
            if ((this.checkStatusOperationCompleted == null)) {
                this.checkStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckStatusOperationCompleted);
            }
            this.InvokeAsync("checkStatus", new object[] {
                        dialogId}, this.checkStatusOperationCompleted, userState);
        }
        
        private void OncheckStatusOperationCompleted(object arg) {
            if ((this.checkStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkStatusCompleted(this, new checkStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public quittung detailDatenAbfragen(string dialogId, long aufId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdSpecified) {
            object[] results = this.Invoke("detailDatenAbfragen", new object[] {
                        dialogId,
                        aufId,
                        aufIdSpecified});
            return ((quittung)(results[0]));
        }
        
        /// <remarks/>
        public void detailDatenAbfragenAsync(string dialogId, long aufId, bool aufIdSpecified) {
            this.detailDatenAbfragenAsync(dialogId, aufId, aufIdSpecified, null);
        }
        
        /// <remarks/>
        public void detailDatenAbfragenAsync(string dialogId, long aufId, bool aufIdSpecified, object userState) {
            if ((this.detailDatenAbfragenOperationCompleted == null)) {
                this.detailDatenAbfragenOperationCompleted = new System.Threading.SendOrPostCallback(this.OndetailDatenAbfragenOperationCompleted);
            }
            this.InvokeAsync("detailDatenAbfragen", new object[] {
                        dialogId,
                        aufId,
                        aufIdSpecified}, this.detailDatenAbfragenOperationCompleted, userState);
        }
        
        private void OndetailDatenAbfragenOperationCompleted(object arg) {
            if ((this.detailDatenAbfragenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.detailDatenAbfragenCompleted(this, new detailDatenAbfragenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string downloadFormblatt() {
            object[] results = this.Invoke("downloadFormblatt", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadFormblattAsync() {
            this.downloadFormblattAsync(null);
        }
        
        /// <remarks/>
        public void downloadFormblattAsync(object userState) {
            if ((this.downloadFormblattOperationCompleted == null)) {
                this.downloadFormblattOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadFormblattOperationCompleted);
            }
            this.InvokeAsync("downloadFormblatt", new object[0], this.downloadFormblattOperationCompleted, userState);
        }
        
        private void OndownloadFormblattOperationCompleted(object arg) {
            if ((this.downloadFormblattCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadFormblattCompleted(this, new downloadFormblattCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public besondereArbeitsunfaehigkeitsursache[] getBesondereArbeitsunfaehigkeitsursacheCodes() {
            object[] results = this.Invoke("getBesondereArbeitsunfaehigkeitsursacheCodes", new object[0]);
            return ((besondereArbeitsunfaehigkeitsursache[])(results[0]));
        }
        
        /// <remarks/>
        public void getBesondereArbeitsunfaehigkeitsursacheCodesAsync() {
            this.getBesondereArbeitsunfaehigkeitsursacheCodesAsync(null);
        }
        
        /// <remarks/>
        public void getBesondereArbeitsunfaehigkeitsursacheCodesAsync(object userState) {
            if ((this.getBesondereArbeitsunfaehigkeitsursacheCodesOperationCompleted == null)) {
                this.getBesondereArbeitsunfaehigkeitsursacheCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBesondereArbeitsunfaehigkeitsursacheCodesOperationCompleted);
            }
            this.InvokeAsync("getBesondereArbeitsunfaehigkeitsursacheCodes", new object[0], this.getBesondereArbeitsunfaehigkeitsursacheCodesOperationCompleted, userState);
        }
        
        private void OngetBesondereArbeitsunfaehigkeitsursacheCodesOperationCompleted(object arg) {
            if ((this.getBesondereArbeitsunfaehigkeitsursacheCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBesondereArbeitsunfaehigkeitsursacheCodesCompleted(this, new getBesondereArbeitsunfaehigkeitsursacheCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public diagnoseCodeTyp[] getDiagnoseCodeTyp() {
            object[] results = this.Invoke("getDiagnoseCodeTyp", new object[0]);
            return ((diagnoseCodeTyp[])(results[0]));
        }
        
        /// <remarks/>
        public void getDiagnoseCodeTypAsync() {
            this.getDiagnoseCodeTypAsync(null);
        }
        
        /// <remarks/>
        public void getDiagnoseCodeTypAsync(object userState) {
            if ((this.getDiagnoseCodeTypOperationCompleted == null)) {
                this.getDiagnoseCodeTypOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDiagnoseCodeTypOperationCompleted);
            }
            this.InvokeAsync("getDiagnoseCodeTyp", new object[0], this.getDiagnoseCodeTypOperationCompleted, userState);
        }
        
        private void OngetDiagnoseCodeTypOperationCompleted(object arg) {
            if ((this.getDiagnoseCodeTypCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDiagnoseCodeTypCompleted(this, new getDiagnoseCodeTypCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public rueckdatierungsgrund[] getRueckdatierungsgrundCodes() {
            object[] results = this.Invoke("getRueckdatierungsgrundCodes", new object[0]);
            return ((rueckdatierungsgrund[])(results[0]));
        }
        
        /// <remarks/>
        public void getRueckdatierungsgrundCodesAsync() {
            this.getRueckdatierungsgrundCodesAsync(null);
        }
        
        /// <remarks/>
        public void getRueckdatierungsgrundCodesAsync(object userState) {
            if ((this.getRueckdatierungsgrundCodesOperationCompleted == null)) {
                this.getRueckdatierungsgrundCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRueckdatierungsgrundCodesOperationCompleted);
            }
            this.InvokeAsync("getRueckdatierungsgrundCodes", new object[0], this.getRueckdatierungsgrundCodesOperationCompleted, userState);
        }
        
        private void OngetRueckdatierungsgrundCodesOperationCompleted(object arg) {
            if ((this.getRueckdatierungsgrundCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRueckdatierungsgrundCodesCompleted(this, new getRueckdatierungsgrundCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public aufSvtProperty[] getSVTs(string dialogId) {
            object[] results = this.Invoke("getSVTs", new object[] {
                        dialogId});
            return ((aufSvtProperty[])(results[0]));
        }
        
        /// <remarks/>
        public void getSVTsAsync(string dialogId) {
            this.getSVTsAsync(dialogId, null);
        }
        
        /// <remarks/>
        public void getSVTsAsync(string dialogId, object userState) {
            if ((this.getSVTsOperationCompleted == null)) {
                this.getSVTsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSVTsOperationCompleted);
            }
            this.InvokeAsync("getSVTs", new object[] {
                        dialogId}, this.getSVTsOperationCompleted, userState);
        }
        
        private void OngetSVTsOperationCompleted(object arg) {
            if ((this.getSVTsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSVTsCompleted(this, new getSVTsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public zusatzdiagnose[] getZusatzdiagnoseCodes() {
            object[] results = this.Invoke("getZusatzdiagnoseCodes", new object[0]);
            return ((zusatzdiagnose[])(results[0]));
        }
        
        /// <remarks/>
        public void getZusatzdiagnoseCodesAsync() {
            this.getZusatzdiagnoseCodesAsync(null);
        }
        
        /// <remarks/>
        public void getZusatzdiagnoseCodesAsync(object userState) {
            if ((this.getZusatzdiagnoseCodesOperationCompleted == null)) {
                this.getZusatzdiagnoseCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZusatzdiagnoseCodesOperationCompleted);
            }
            this.InvokeAsync("getZusatzdiagnoseCodes", new object[0], this.getZusatzdiagnoseCodesOperationCompleted, userState);
        }
        
        private void OngetZusatzdiagnoseCodesOperationCompleted(object arg) {
            if ((this.getZusatzdiagnoseCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getZusatzdiagnoseCodesCompleted(this, new getZusatzdiagnoseCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public quittung meldungAendern(string dialogId, long aufId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdSpecified, int aufIdVersion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdVersionSpecified, meldungsdaten meldungNeu, string meldungsArt, bool forceExecution, [System.Xml.Serialization.XmlIgnoreAttribute()] bool forceExecutionSpecified) {
            object[] results = this.Invoke("meldungAendern", new object[] {
                        dialogId,
                        aufId,
                        aufIdSpecified,
                        aufIdVersion,
                        aufIdVersionSpecified,
                        meldungNeu,
                        meldungsArt,
                        forceExecution,
                        forceExecutionSpecified});
            return ((quittung)(results[0]));
        }
        
        /// <remarks/>
        public void meldungAendernAsync(string dialogId, long aufId, bool aufIdSpecified, int aufIdVersion, bool aufIdVersionSpecified, meldungsdaten meldungNeu, string meldungsArt, bool forceExecution, bool forceExecutionSpecified) {
            this.meldungAendernAsync(dialogId, aufId, aufIdSpecified, aufIdVersion, aufIdVersionSpecified, meldungNeu, meldungsArt, forceExecution, forceExecutionSpecified, null);
        }
        
        /// <remarks/>
        public void meldungAendernAsync(string dialogId, long aufId, bool aufIdSpecified, int aufIdVersion, bool aufIdVersionSpecified, meldungsdaten meldungNeu, string meldungsArt, bool forceExecution, bool forceExecutionSpecified, object userState) {
            if ((this.meldungAendernOperationCompleted == null)) {
                this.meldungAendernOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmeldungAendernOperationCompleted);
            }
            this.InvokeAsync("meldungAendern", new object[] {
                        dialogId,
                        aufId,
                        aufIdSpecified,
                        aufIdVersion,
                        aufIdVersionSpecified,
                        meldungNeu,
                        meldungsArt,
                        forceExecution,
                        forceExecutionSpecified}, this.meldungAendernOperationCompleted, userState);
        }
        
        private void OnmeldungAendernOperationCompleted(object arg) {
            if ((this.meldungAendernCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.meldungAendernCompleted(this, new meldungAendernCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public quittung[] meldungAnlegen(string dialogId, string cardReaderId, meldungsdaten meldungsdaten, string meldungsArt, person person, bool forceExecution, [System.Xml.Serialization.XmlIgnoreAttribute()] bool forceExecutionSpecified, bool ungeprueft, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ungeprueftSpecified, bool offeneMeldungenSuchen, [System.Xml.Serialization.XmlIgnoreAttribute()] bool offeneMeldungenSuchenSpecified) {
            object[] results = this.Invoke("meldungAnlegen", new object[] {
                        dialogId,
                        cardReaderId,
                        meldungsdaten,
                        meldungsArt,
                        person,
                        forceExecution,
                        forceExecutionSpecified,
                        ungeprueft,
                        ungeprueftSpecified,
                        offeneMeldungenSuchen,
                        offeneMeldungenSuchenSpecified});
            return ((quittung[])(results[0]));
        }
        
        /// <remarks/>
        public void meldungAnlegenAsync(string dialogId, string cardReaderId, meldungsdaten meldungsdaten, string meldungsArt, person person, bool forceExecution, bool forceExecutionSpecified, bool ungeprueft, bool ungeprueftSpecified, bool offeneMeldungenSuchen, bool offeneMeldungenSuchenSpecified) {
            this.meldungAnlegenAsync(dialogId, cardReaderId, meldungsdaten, meldungsArt, person, forceExecution, forceExecutionSpecified, ungeprueft, ungeprueftSpecified, offeneMeldungenSuchen, offeneMeldungenSuchenSpecified, null);
        }
        
        /// <remarks/>
        public void meldungAnlegenAsync(string dialogId, string cardReaderId, meldungsdaten meldungsdaten, string meldungsArt, person person, bool forceExecution, bool forceExecutionSpecified, bool ungeprueft, bool ungeprueftSpecified, bool offeneMeldungenSuchen, bool offeneMeldungenSuchenSpecified, object userState) {
            if ((this.meldungAnlegenOperationCompleted == null)) {
                this.meldungAnlegenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmeldungAnlegenOperationCompleted);
            }
            this.InvokeAsync("meldungAnlegen", new object[] {
                        dialogId,
                        cardReaderId,
                        meldungsdaten,
                        meldungsArt,
                        person,
                        forceExecution,
                        forceExecutionSpecified,
                        ungeprueft,
                        ungeprueftSpecified,
                        offeneMeldungenSuchen,
                        offeneMeldungenSuchenSpecified}, this.meldungAnlegenOperationCompleted, userState);
        }
        
        private void OnmeldungAnlegenOperationCompleted(object arg) {
            if ((this.meldungAnlegenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.meldungAnlegenCompleted(this, new meldungAnlegenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void meldungStornieren(string dialogId, long aufId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdSpecified, int aufIdVersion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aufIdVersionSpecified) {
            this.Invoke("meldungStornieren", new object[] {
                        dialogId,
                        aufId,
                        aufIdSpecified,
                        aufIdVersion,
                        aufIdVersionSpecified});
        }
        
        /// <remarks/>
        public void meldungStornierenAsync(string dialogId, long aufId, bool aufIdSpecified, int aufIdVersion, bool aufIdVersionSpecified) {
            this.meldungStornierenAsync(dialogId, aufId, aufIdSpecified, aufIdVersion, aufIdVersionSpecified, null);
        }
        
        /// <remarks/>
        public void meldungStornierenAsync(string dialogId, long aufId, bool aufIdSpecified, int aufIdVersion, bool aufIdVersionSpecified, object userState) {
            if ((this.meldungStornierenOperationCompleted == null)) {
                this.meldungStornierenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmeldungStornierenOperationCompleted);
            }
            this.InvokeAsync("meldungStornieren", new object[] {
                        dialogId,
                        aufId,
                        aufIdSpecified,
                        aufIdVersion,
                        aufIdVersionSpecified}, this.meldungStornierenOperationCompleted, userState);
        }
        
        private void OnmeldungStornierenOperationCompleted(object arg) {
            if ((this.meldungStornierenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.meldungStornierenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public aufSuchergebnis[] meldungenFuerSvPersonSuchen(string dialogId, string cardReaderId, suchparameterSvPerson suchparameterSvPerson) {
            object[] results = this.Invoke("meldungenFuerSvPersonSuchen", new object[] {
                        dialogId,
                        cardReaderId,
                        suchparameterSvPerson});
            return ((aufSuchergebnis[])(results[0]));
        }
        
        /// <remarks/>
        public void meldungenFuerSvPersonSuchenAsync(string dialogId, string cardReaderId, suchparameterSvPerson suchparameterSvPerson) {
            this.meldungenFuerSvPersonSuchenAsync(dialogId, cardReaderId, suchparameterSvPerson, null);
        }
        
        /// <remarks/>
        public void meldungenFuerSvPersonSuchenAsync(string dialogId, string cardReaderId, suchparameterSvPerson suchparameterSvPerson, object userState) {
            if ((this.meldungenFuerSvPersonSuchenOperationCompleted == null)) {
                this.meldungenFuerSvPersonSuchenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmeldungenFuerSvPersonSuchenOperationCompleted);
            }
            this.InvokeAsync("meldungenFuerSvPersonSuchen", new object[] {
                        dialogId,
                        cardReaderId,
                        suchparameterSvPerson}, this.meldungenFuerSvPersonSuchenOperationCompleted, userState);
        }
        
        private void OnmeldungenFuerSvPersonSuchenOperationCompleted(object arg) {
            if ((this.meldungenFuerSvPersonSuchenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.meldungenFuerSvPersonSuchenCompleted(this, new meldungenFuerSvPersonSuchenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.aum.client.chipkarte.at", ResponseNamespace="http://soap.aum.client.chipkarte.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public aufSuchergebnis[] selbstErstellteMeldungenSuchen(string dialogId, suchkriterien suche) {
            object[] results = this.Invoke("selbstErstellteMeldungenSuchen", new object[] {
                        dialogId,
                        suche});
            return ((aufSuchergebnis[])(results[0]));
        }
        
        /// <remarks/>
        public void selbstErstellteMeldungenSuchenAsync(string dialogId, suchkriterien suche) {
            this.selbstErstellteMeldungenSuchenAsync(dialogId, suche, null);
        }
        
        /// <remarks/>
        public void selbstErstellteMeldungenSuchenAsync(string dialogId, suchkriterien suche, object userState) {
            if ((this.selbstErstellteMeldungenSuchenOperationCompleted == null)) {
                this.selbstErstellteMeldungenSuchenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnselbstErstellteMeldungenSuchenOperationCompleted);
            }
            this.InvokeAsync("selbstErstellteMeldungenSuchen", new object[] {
                        dialogId,
                        suche}, this.selbstErstellteMeldungenSuchenOperationCompleted, userState);
        }
        
        private void OnselbstErstellteMeldungenSuchenOperationCompleted(object arg) {
            if ((this.selbstErstellteMeldungenSuchenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.selbstErstellteMeldungenSuchenCompleted(this, new selbstErstellteMeldungenSuchenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class aufSuchergebnis {
        
        private string abweichendeAusgehzeitBis1Field;
        
        private string abweichendeAusgehzeitBis2Field;
        
        private string abweichendeAusgehzeitVon1Field;
        
        private string abweichendeAusgehzeitVon2Field;
        
        private string afMelderField;
        
        private string arbeitsunfaehigBisField;
        
        private string arbeitsunfaehigVonField;
        
        private string auErgaenzerField;
        
        private long aufIDField;
        
        private bool aufIDFieldSpecified;
        
        private int aufVersionField;
        
        private bool aufVersionFieldSpecified;
        
        private string ausstellungsdatumField;
        
        private bool bettruheField;
        
        private bool bettruheFieldSpecified;
        
        private bool editierbarField;
        
        private bool editierbarFieldSpecified;
        
        private string geburtsDatumField;
        
        private string meldungsartField;
        
        private bool selbsterstelltAFField;
        
        private bool selbsterstelltAFFieldSpecified;
        
        private bool selbsterstelltAUField;
        
        private bool selbsterstelltAUFieldSpecified;
        
        private string svNummerField;
        
        private string svtCodeField;
        
        private bool ungeprueftField;
        
        private bool ungeprueftFieldSpecified;
        
        private string vornameField;
        
        private string zunameField;
        
        /// <remarks/>
        public string abweichendeAusgehzeitBis1 {
            get {
                return this.abweichendeAusgehzeitBis1Field;
            }
            set {
                this.abweichendeAusgehzeitBis1Field = value;
            }
        }
        
        /// <remarks/>
        public string abweichendeAusgehzeitBis2 {
            get {
                return this.abweichendeAusgehzeitBis2Field;
            }
            set {
                this.abweichendeAusgehzeitBis2Field = value;
            }
        }
        
        /// <remarks/>
        public string abweichendeAusgehzeitVon1 {
            get {
                return this.abweichendeAusgehzeitVon1Field;
            }
            set {
                this.abweichendeAusgehzeitVon1Field = value;
            }
        }
        
        /// <remarks/>
        public string abweichendeAusgehzeitVon2 {
            get {
                return this.abweichendeAusgehzeitVon2Field;
            }
            set {
                this.abweichendeAusgehzeitVon2Field = value;
            }
        }
        
        /// <remarks/>
        public string afMelder {
            get {
                return this.afMelderField;
            }
            set {
                this.afMelderField = value;
            }
        }
        
        /// <remarks/>
        public string arbeitsunfaehigBis {
            get {
                return this.arbeitsunfaehigBisField;
            }
            set {
                this.arbeitsunfaehigBisField = value;
            }
        }
        
        /// <remarks/>
        public string arbeitsunfaehigVon {
            get {
                return this.arbeitsunfaehigVonField;
            }
            set {
                this.arbeitsunfaehigVonField = value;
            }
        }
        
        /// <remarks/>
        public string auErgaenzer {
            get {
                return this.auErgaenzerField;
            }
            set {
                this.auErgaenzerField = value;
            }
        }
        
        /// <remarks/>
        public long aufID {
            get {
                return this.aufIDField;
            }
            set {
                this.aufIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aufIDSpecified {
            get {
                return this.aufIDFieldSpecified;
            }
            set {
                this.aufIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int aufVersion {
            get {
                return this.aufVersionField;
            }
            set {
                this.aufVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aufVersionSpecified {
            get {
                return this.aufVersionFieldSpecified;
            }
            set {
                this.aufVersionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ausstellungsdatum {
            get {
                return this.ausstellungsdatumField;
            }
            set {
                this.ausstellungsdatumField = value;
            }
        }
        
        /// <remarks/>
        public bool bettruhe {
            get {
                return this.bettruheField;
            }
            set {
                this.bettruheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bettruheSpecified {
            get {
                return this.bettruheFieldSpecified;
            }
            set {
                this.bettruheFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool editierbar {
            get {
                return this.editierbarField;
            }
            set {
                this.editierbarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool editierbarSpecified {
            get {
                return this.editierbarFieldSpecified;
            }
            set {
                this.editierbarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string geburtsDatum {
            get {
                return this.geburtsDatumField;
            }
            set {
                this.geburtsDatumField = value;
            }
        }
        
        /// <remarks/>
        public string meldungsart {
            get {
                return this.meldungsartField;
            }
            set {
                this.meldungsartField = value;
            }
        }
        
        /// <remarks/>
        public bool selbsterstelltAF {
            get {
                return this.selbsterstelltAFField;
            }
            set {
                this.selbsterstelltAFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selbsterstelltAFSpecified {
            get {
                return this.selbsterstelltAFFieldSpecified;
            }
            set {
                this.selbsterstelltAFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool selbsterstelltAU {
            get {
                return this.selbsterstelltAUField;
            }
            set {
                this.selbsterstelltAUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selbsterstelltAUSpecified {
            get {
                return this.selbsterstelltAUFieldSpecified;
            }
            set {
                this.selbsterstelltAUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string svNummer {
            get {
                return this.svNummerField;
            }
            set {
                this.svNummerField = value;
            }
        }
        
        /// <remarks/>
        public string svtCode {
            get {
                return this.svtCodeField;
            }
            set {
                this.svtCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool ungeprueft {
            get {
                return this.ungeprueftField;
            }
            set {
                this.ungeprueftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ungeprueftSpecified {
            get {
                return this.ungeprueftFieldSpecified;
            }
            set {
                this.ungeprueftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
            }
        }
        
        /// <remarks/>
        public string zuname {
            get {
                return this.zunameField;
            }
            set {
                this.zunameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class suchkriterien {
        
        private string erstellungAbField;
        
        private string erstellungBisField;
        
        private string meldungsartField;
        
        private string svNummerField;
        
        private string vornameField;
        
        private string zunameField;
        
        /// <remarks/>
        public string erstellungAb {
            get {
                return this.erstellungAbField;
            }
            set {
                this.erstellungAbField = value;
            }
        }
        
        /// <remarks/>
        public string erstellungBis {
            get {
                return this.erstellungBisField;
            }
            set {
                this.erstellungBisField = value;
            }
        }
        
        /// <remarks/>
        public string meldungsart {
            get {
                return this.meldungsartField;
            }
            set {
                this.meldungsartField = value;
            }
        }
        
        /// <remarks/>
        public string svNummer {
            get {
                return this.svNummerField;
            }
            set {
                this.svNummerField = value;
            }
        }
        
        /// <remarks/>
        public string vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
            }
        }
        
        /// <remarks/>
        public string zuname {
            get {
                return this.zunameField;
            }
            set {
                this.zunameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class suchparameterSvPerson {
        
        private string erstellungAbField;
        
        private string erstellungBisField;
        
        private string meldungsartField;
        
        private string svNummerField;
        
        /// <remarks/>
        public string erstellungAb {
            get {
                return this.erstellungAbField;
            }
            set {
                this.erstellungAbField = value;
            }
        }
        
        /// <remarks/>
        public string erstellungBis {
            get {
                return this.erstellungBisField;
            }
            set {
                this.erstellungBisField = value;
            }
        }
        
        /// <remarks/>
        public string meldungsart {
            get {
                return this.meldungsartField;
            }
            set {
                this.meldungsartField = value;
            }
        }
        
        /// <remarks/>
        public string svNummer {
            get {
                return this.svNummerField;
            }
            set {
                this.svNummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class zusatzdiagnose {
        
        private string bezeichnungField;
        
        private string codeField;
        
        /// <remarks/>
        public string bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class aufSvtProperty {
        
        private bool asvgField;
        
        private bool asvgFieldSpecified;
        
        private string ausgehzeitBis1Field;
        
        private string ausgehzeitBis2Field;
        
        private string ausgehzeitVon1Field;
        
        private string ausgehzeitVon2Field;
        
        private string ekvkCodeField;
        
        private string ekvkNameField;
        
        private string kurzbezeichnungField;
        
        private string svtCodeField;
        
        /// <remarks/>
        public bool asvg {
            get {
                return this.asvgField;
            }
            set {
                this.asvgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool asvgSpecified {
            get {
                return this.asvgFieldSpecified;
            }
            set {
                this.asvgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ausgehzeitBis1 {
            get {
                return this.ausgehzeitBis1Field;
            }
            set {
                this.ausgehzeitBis1Field = value;
            }
        }
        
        /// <remarks/>
        public string ausgehzeitBis2 {
            get {
                return this.ausgehzeitBis2Field;
            }
            set {
                this.ausgehzeitBis2Field = value;
            }
        }
        
        /// <remarks/>
        public string ausgehzeitVon1 {
            get {
                return this.ausgehzeitVon1Field;
            }
            set {
                this.ausgehzeitVon1Field = value;
            }
        }
        
        /// <remarks/>
        public string ausgehzeitVon2 {
            get {
                return this.ausgehzeitVon2Field;
            }
            set {
                this.ausgehzeitVon2Field = value;
            }
        }
        
        /// <remarks/>
        public string ekvkCode {
            get {
                return this.ekvkCodeField;
            }
            set {
                this.ekvkCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ekvkName {
            get {
                return this.ekvkNameField;
            }
            set {
                this.ekvkNameField = value;
            }
        }
        
        /// <remarks/>
        public string kurzbezeichnung {
            get {
                return this.kurzbezeichnungField;
            }
            set {
                this.kurzbezeichnungField = value;
            }
        }
        
        /// <remarks/>
        public string svtCode {
            get {
                return this.svtCodeField;
            }
            set {
                this.svtCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class rueckdatierungsgrund {
        
        private string beschreibungField;
        
        private string codeField;
        
        /// <remarks/>
        public string beschreibung {
            get {
                return this.beschreibungField;
            }
            set {
                this.beschreibungField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class diagnoseCodeTyp {
        
        private string bezeichnungField;
        
        private string codeField;
        
        /// <remarks/>
        public string bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class besondereArbeitsunfaehigkeitsursache {
        
        private string bezeichnungField;
        
        private string codeField;
        
        /// <remarks/>
        public string bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class person {
        
        private string druckVornameField;
        
        private string druckZunameField;
        
        private string ekvkNummerField;
        
        private string ekvkTraegerField;
        
        private string geburtsdatumField;
        
        private string geschlechtField;
        
        private string svNummerField;
        
        private string vornameField;
        
        private string zunameField;
        
        /// <remarks/>
        public string druckVorname {
            get {
                return this.druckVornameField;
            }
            set {
                this.druckVornameField = value;
            }
        }
        
        /// <remarks/>
        public string druckZuname {
            get {
                return this.druckZunameField;
            }
            set {
                this.druckZunameField = value;
            }
        }
        
        /// <remarks/>
        public string ekvkNummer {
            get {
                return this.ekvkNummerField;
            }
            set {
                this.ekvkNummerField = value;
            }
        }
        
        /// <remarks/>
        public string ekvkTraeger {
            get {
                return this.ekvkTraegerField;
            }
            set {
                this.ekvkTraegerField = value;
            }
        }
        
        /// <remarks/>
        public string geburtsdatum {
            get {
                return this.geburtsdatumField;
            }
            set {
                this.geburtsdatumField = value;
            }
        }
        
        /// <remarks/>
        public string geschlecht {
            get {
                return this.geschlechtField;
            }
            set {
                this.geschlechtField = value;
            }
        }
        
        /// <remarks/>
        public string svNummer {
            get {
                return this.svNummerField;
            }
            set {
                this.svNummerField = value;
            }
        }
        
        /// <remarks/>
        public string vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
            }
        }
        
        /// <remarks/>
        public string zuname {
            get {
                return this.zunameField;
            }
            set {
                this.zunameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class meldungsdaten {
        
        private string abweichendeAusgehzeitBis1Field;
        
        private string abweichendeAusgehzeitBis2Field;
        
        private string abweichendeAusgehzeitVon1Field;
        
        private string abweichendeAusgehzeitVon2Field;
        
        private string arbeitsunfaehigBisField;
        
        private string arbeitsunfaehigVonField;
        
        private string behandlungsDatumField;
        
        private int berufskrankheitField;
        
        private bool berufskrankheitFieldSpecified;
        
        private string besondereArbeitsunfaehigkeitsursacheCodeField;
        
        private string besondereMitteilungAnSVTField;
        
        private bool bettruheField;
        
        private bool bettruheFieldSpecified;
        
        private string diagnoseField;
        
        private string diagnoseCodeField;
        
        private string diagnoseCodeTypField;
        
        private string gehunfaehigBisField;
        
        private string gipsBisField;
        
        private string krankenhausaufenthaltBisField;
        
        private string krankenhausaufenthaltVonField;
        
        private string ortField;
        
        private string plzField;
        
        private string rueckdatierungsgrundCodeField;
        
        private string strasseField;
        
        private string staatencodeField;
        
        private bool stromunfallField;
        
        private bool stromunfallFieldSpecified;
        
        private string svtCodeField;
        
        private string voraussichtlichArbeitsunfaehigBisField;
        
        private string wiederbestellungField;
        
        private string zusatzdiagnoseCodeField;
        
        /// <remarks/>
        public string abweichendeAusgehzeitBis1 {
            get {
                return this.abweichendeAusgehzeitBis1Field;
            }
            set {
                this.abweichendeAusgehzeitBis1Field = value;
            }
        }
        
        /// <remarks/>
        public string abweichendeAusgehzeitBis2 {
            get {
                return this.abweichendeAusgehzeitBis2Field;
            }
            set {
                this.abweichendeAusgehzeitBis2Field = value;
            }
        }
        
        /// <remarks/>
        public string abweichendeAusgehzeitVon1 {
            get {
                return this.abweichendeAusgehzeitVon1Field;
            }
            set {
                this.abweichendeAusgehzeitVon1Field = value;
            }
        }
        
        /// <remarks/>
        public string abweichendeAusgehzeitVon2 {
            get {
                return this.abweichendeAusgehzeitVon2Field;
            }
            set {
                this.abweichendeAusgehzeitVon2Field = value;
            }
        }
        
        /// <remarks/>
        public string arbeitsunfaehigBis {
            get {
                return this.arbeitsunfaehigBisField;
            }
            set {
                this.arbeitsunfaehigBisField = value;
            }
        }
        
        /// <remarks/>
        public string arbeitsunfaehigVon {
            get {
                return this.arbeitsunfaehigVonField;
            }
            set {
                this.arbeitsunfaehigVonField = value;
            }
        }
        
        /// <remarks/>
        public string behandlungsDatum {
            get {
                return this.behandlungsDatumField;
            }
            set {
                this.behandlungsDatumField = value;
            }
        }
        
        /// <remarks/>
        public int berufskrankheit {
            get {
                return this.berufskrankheitField;
            }
            set {
                this.berufskrankheitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool berufskrankheitSpecified {
            get {
                return this.berufskrankheitFieldSpecified;
            }
            set {
                this.berufskrankheitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string besondereArbeitsunfaehigkeitsursacheCode {
            get {
                return this.besondereArbeitsunfaehigkeitsursacheCodeField;
            }
            set {
                this.besondereArbeitsunfaehigkeitsursacheCodeField = value;
            }
        }
        
        /// <remarks/>
        public string besondereMitteilungAnSVT {
            get {
                return this.besondereMitteilungAnSVTField;
            }
            set {
                this.besondereMitteilungAnSVTField = value;
            }
        }
        
        /// <remarks/>
        public bool bettruhe {
            get {
                return this.bettruheField;
            }
            set {
                this.bettruheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bettruheSpecified {
            get {
                return this.bettruheFieldSpecified;
            }
            set {
                this.bettruheFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string diagnose {
            get {
                return this.diagnoseField;
            }
            set {
                this.diagnoseField = value;
            }
        }
        
        /// <remarks/>
        public string diagnoseCode {
            get {
                return this.diagnoseCodeField;
            }
            set {
                this.diagnoseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string diagnoseCodeTyp {
            get {
                return this.diagnoseCodeTypField;
            }
            set {
                this.diagnoseCodeTypField = value;
            }
        }
        
        /// <remarks/>
        public string gehunfaehigBis {
            get {
                return this.gehunfaehigBisField;
            }
            set {
                this.gehunfaehigBisField = value;
            }
        }
        
        /// <remarks/>
        public string gipsBis {
            get {
                return this.gipsBisField;
            }
            set {
                this.gipsBisField = value;
            }
        }
        
        /// <remarks/>
        public string krankenhausaufenthaltBis {
            get {
                return this.krankenhausaufenthaltBisField;
            }
            set {
                this.krankenhausaufenthaltBisField = value;
            }
        }
        
        /// <remarks/>
        public string krankenhausaufenthaltVon {
            get {
                return this.krankenhausaufenthaltVonField;
            }
            set {
                this.krankenhausaufenthaltVonField = value;
            }
        }
        
        /// <remarks/>
        public string ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
            }
        }
        
        /// <remarks/>
        public string plz {
            get {
                return this.plzField;
            }
            set {
                this.plzField = value;
            }
        }
        
        /// <remarks/>
        public string rueckdatierungsgrundCode {
            get {
                return this.rueckdatierungsgrundCodeField;
            }
            set {
                this.rueckdatierungsgrundCodeField = value;
            }
        }
        
        /// <remarks/>
        public string strasse {
            get {
                return this.strasseField;
            }
            set {
                this.strasseField = value;
            }
        }
        
        /// <remarks/>
        public string staatencode {
            get {
                return this.staatencodeField;
            }
            set {
                this.staatencodeField = value;
            }
        }
        
        /// <remarks/>
        public bool stromunfall {
            get {
                return this.stromunfallField;
            }
            set {
                this.stromunfallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stromunfallSpecified {
            get {
                return this.stromunfallFieldSpecified;
            }
            set {
                this.stromunfallFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string svtCode {
            get {
                return this.svtCodeField;
            }
            set {
                this.svtCodeField = value;
            }
        }
        
        /// <remarks/>
        public string voraussichtlichArbeitsunfaehigBis {
            get {
                return this.voraussichtlichArbeitsunfaehigBisField;
            }
            set {
                this.voraussichtlichArbeitsunfaehigBisField = value;
            }
        }
        
        /// <remarks/>
        public string wiederbestellung {
            get {
                return this.wiederbestellungField;
            }
            set {
                this.wiederbestellungField = value;
            }
        }
        
        /// <remarks/>
        public string zusatzdiagnoseCode {
            get {
                return this.zusatzdiagnoseCodeField;
            }
            set {
                this.zusatzdiagnoseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.aum.client.chipkarte.at")]
    public partial class quittung {
        
        private string afMelderField;
        
        private string auErgaenzerField;
        
        private string ausstellungsDatumField;
        
        private bool editierbarField;
        
        private bool editierbarFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string meldungsartField;
        
        private meldungsdaten meldungsdatenField;
        
        private person personendatenField;
        
        private bool selbsterstelltAFField;
        
        private bool selbsterstelltAFFieldSpecified;
        
        private bool selbsterstelltAUField;
        
        private bool selbsterstelltAUFieldSpecified;
        
        private bool ungeprueftField;
        
        private bool ungeprueftFieldSpecified;
        
        private int versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        public string afMelder {
            get {
                return this.afMelderField;
            }
            set {
                this.afMelderField = value;
            }
        }
        
        /// <remarks/>
        public string auErgaenzer {
            get {
                return this.auErgaenzerField;
            }
            set {
                this.auErgaenzerField = value;
            }
        }
        
        /// <remarks/>
        public string ausstellungsDatum {
            get {
                return this.ausstellungsDatumField;
            }
            set {
                this.ausstellungsDatumField = value;
            }
        }
        
        /// <remarks/>
        public bool editierbar {
            get {
                return this.editierbarField;
            }
            set {
                this.editierbarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool editierbarSpecified {
            get {
                return this.editierbarFieldSpecified;
            }
            set {
                this.editierbarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string meldungsart {
            get {
                return this.meldungsartField;
            }
            set {
                this.meldungsartField = value;
            }
        }
        
        /// <remarks/>
        public meldungsdaten meldungsdaten {
            get {
                return this.meldungsdatenField;
            }
            set {
                this.meldungsdatenField = value;
            }
        }
        
        /// <remarks/>
        public person personendaten {
            get {
                return this.personendatenField;
            }
            set {
                this.personendatenField = value;
            }
        }
        
        /// <remarks/>
        public bool selbsterstelltAF {
            get {
                return this.selbsterstelltAFField;
            }
            set {
                this.selbsterstelltAFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selbsterstelltAFSpecified {
            get {
                return this.selbsterstelltAFFieldSpecified;
            }
            set {
                this.selbsterstelltAFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool selbsterstelltAU {
            get {
                return this.selbsterstelltAUField;
            }
            set {
                this.selbsterstelltAUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selbsterstelltAUSpecified {
            get {
                return this.selbsterstelltAUFieldSpecified;
            }
            set {
                this.selbsterstelltAUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ungeprueft {
            get {
                return this.ungeprueftField;
            }
            set {
                this.ungeprueftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ungeprueftSpecified {
            get {
                return this.ungeprueftFieldSpecified;
            }
            set {
                this.ungeprueftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.base.client.chipkarte.at")]
    public partial class property {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void auEndeBearbeitenCompletedEventHandler(object sender, auEndeBearbeitenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class auEndeBearbeitenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal auEndeBearbeitenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public aufSuchergebnis Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((aufSuchergebnis)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void checkStatusCompletedEventHandler(object sender, checkStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public property[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((property[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void detailDatenAbfragenCompletedEventHandler(object sender, detailDatenAbfragenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detailDatenAbfragenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal detailDatenAbfragenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public quittung Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((quittung)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadFormblattCompletedEventHandler(object sender, downloadFormblattCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadFormblattCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadFormblattCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getBesondereArbeitsunfaehigkeitsursacheCodesCompletedEventHandler(object sender, getBesondereArbeitsunfaehigkeitsursacheCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBesondereArbeitsunfaehigkeitsursacheCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBesondereArbeitsunfaehigkeitsursacheCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public besondereArbeitsunfaehigkeitsursache[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((besondereArbeitsunfaehigkeitsursache[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDiagnoseCodeTypCompletedEventHandler(object sender, getDiagnoseCodeTypCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDiagnoseCodeTypCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDiagnoseCodeTypCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public diagnoseCodeTyp[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((diagnoseCodeTyp[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getRueckdatierungsgrundCodesCompletedEventHandler(object sender, getRueckdatierungsgrundCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRueckdatierungsgrundCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRueckdatierungsgrundCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rueckdatierungsgrund[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rueckdatierungsgrund[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getSVTsCompletedEventHandler(object sender, getSVTsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSVTsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSVTsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public aufSvtProperty[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((aufSvtProperty[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getZusatzdiagnoseCodesCompletedEventHandler(object sender, getZusatzdiagnoseCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getZusatzdiagnoseCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getZusatzdiagnoseCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public zusatzdiagnose[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((zusatzdiagnose[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void meldungAendernCompletedEventHandler(object sender, meldungAendernCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class meldungAendernCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal meldungAendernCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public quittung Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((quittung)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void meldungAnlegenCompletedEventHandler(object sender, meldungAnlegenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class meldungAnlegenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal meldungAnlegenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public quittung[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((quittung[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void meldungStornierenCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void meldungenFuerSvPersonSuchenCompletedEventHandler(object sender, meldungenFuerSvPersonSuchenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class meldungenFuerSvPersonSuchenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal meldungenFuerSvPersonSuchenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public aufSuchergebnis[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((aufSuchergebnis[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void selbstErstellteMeldungenSuchenCompletedEventHandler(object sender, selbstErstellteMeldungenSuchenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class selbstErstellteMeldungenSuchenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal selbstErstellteMeldungenSuchenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public aufSuchergebnis[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((aufSuchergebnis[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591